name: fun

on: 
    push:
      branches:
        -main
    workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu - latest
    steps:
      - run: echo ":wave Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
